entity_templates = {}

entity_templates["ACTOR"] = {C_TRANSFORM, C_MOVABLE, C_DRAWABLE, C_COLLIDABLE, C_DAMAGEABLE, C_PHYSICS, C_CONTROL}
entity_templates["SLIME"] = {C_TRANSFORM, C_MOVABLE, C_DRAWABLE, C_COLLIDABLE, C_DAMAGEABLE, C_DAMAGING, C_CONTROL, C_STATEMACHINE} 